sudo: required
services:
  - docker

before_install:
  - docker build -t nicksv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nicksv/react-test npm test

after_success:
  - docker build -t nicksv/multi-client ./client
  - docker build -t nicksv/multi-worker ./worker
  - docker build -t nicksv/multi-nginx ./nginx
  - docker build -t nicksv/multi-server ./server

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push nicksv/multi-client
  - docker push nicksv/multi-worker
  - docker push nicksv/multi-nginx
  - docker push nicksv/multi-server

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-543551216514"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"